---

- name: vagrant .ssh dir
  file: name=/home/vagrant/.ssh state=directory
        owner=vagrant group=vagrant mode=0700

- name: vagrant pubkey
  get_url: url=https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub
           dest=/home/vagrant/.ssh/authorized_keys
           owner=vagrant group=vagrant mode=0600
